#pragma once

#define PWVIZ_SAMPLE_RATE 48000
#define PWVIZ_CHANNELS 2
#define PWVIZ_FFT_SIZE 2048
#define PWVIZ_BAR_COUNT 64
#define PWVIZ_RING_SIZE (PWVIZ_SAMPLE_RATE * 4)

#define PWVIZ_HANDLE_HEIGHT 22
#define PWVIZ_RESIZE_GRIP_SIZE 28
#define PWVIZ_MIN_WINDOW_WIDTH 240
#define PWVIZ_MIN_WINDOW_HEIGHT 90

#define PWVIZ_SPECTRUM_TOP_PADDING 28
#define PWVIZ_SPECTRUM_BOTTOM_PADDING 6
#define PWVIZ_PEAK_HOLD_FRAMES 8
#define PWVIZ_PEAK_FALL_PER_FRAME 0.012f
